/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mn_tck_semitone_PianoEngine */

#ifndef _Included_mn_tck_semitone_PianoEngine
#define _Included_mn_tck_semitone_PianoEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    createPianoEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mn_tck_semitone_PianoEngine_createPianoEngine
  (JNIEnv *, jclass);

/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    destroyPianoEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mn_tck_semitone_PianoEngine_destroyPianoEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    setSampleRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mn_tck_semitone_PianoEngine_setSampleRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    setFramesPerBurst
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mn_tck_semitone_PianoEngine_setFramesPerBurst
  (JNIEnv *, jclass, jint);

/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    doPlay
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_mn_tck_semitone_PianoEngine_doPlay
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     mn_tck_semitone_PianoEngine
 * Method:    doPlay
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_mn_tck_semitone_PianoEngine_doStop
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
